//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace PaintDotNet.IndirectUI.Xml.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("IndirectUI", Namespace="", IsNullable=false)]
    public partial class Container {
        
        private Panel[] panelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Panel", Order=0)]
        public Panel[] Panel {
            get {
                return this.panelField;
            }
            set {
                this.panelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Panel {
        
        private Controls controlsField;
        
        private string nameField;
        
        private string textField;
        
        private string toolTipTextField;
        
        /// <remarks/>
        public Controls Controls {
            get {
                return this.controlsField;
            }
            set {
                this.controlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string ToolTipText {
            get {
                return this.toolTipTextField;
            }
            set {
                this.toolTipTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Controls {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngleChooser", typeof(AngleChooser), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CheckBox", typeof(CheckBox), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ColorWheel", typeof(ColorWheel), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Container", typeof(Container), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleSlider", typeof(DoubleSlider), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVector3RollBallAndSlider", typeof(DoubleVector3RollBallAndSlider), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVector3Slider", typeof(DoubleVector3Slider), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVectorPanAndSlider", typeof(DoubleVectorPanAndSlider), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVectorSlider", typeof(DoubleVectorSlider), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DropDown", typeof(DropDown), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FileChooser", typeof(FileChooser), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FolderChooser", typeof(FolderChooser), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IncrementButton", typeof(IncrementButton), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IntSlider", typeof(IntSlider), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LinkLabel", typeof(LinkLabel), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RadioButton", typeof(RadioButton), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TextBox", typeof(TextBox), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AngleChooser : BaseControl {
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        private double minValueField;
        
        private double maxValueField;
        
        private double upDownIncrementField;
        
        private bool showResetButtonField;
        
        public AngleChooser() {
            this.minValueField = 0D;
            this.maxValueField = 360D;
            this.upDownIncrementField = 1D;
            this.showResetButtonField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(360D)]
        public double MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double UpDownIncrement {
            get {
                return this.upDownIncrementField;
            }
            set {
                this.upDownIncrementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ShowResetButton {
            get {
                return this.showResetButtonField;
            }
            set {
                this.showResetButtonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StaticListChoice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RadioButton))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DropDown))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinkLabel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderChooser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileChooser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextBox))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVector3))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVector3RollBallAndSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVector3Slider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVectorPanAndSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVectorSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckBox))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleChooser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncrementButton))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ColorWheel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntSlider))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseControl {
        
        private object[] itemsField;
        
        private string nameField;
        
        private bool readOnlyField;
        
        private ValidationFailureResult onValidationFailureField;
        
        private string descriptionField;
        
        private string displayNameField;
        
        public BaseControl() {
            this.readOnlyField = false;
            this.onValidationFailureField = ValidationFailureResult.Clamp;
            this.descriptionField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundToBoolean", typeof(ReadOnlyBoundToBoolean), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BoundToNameValues", typeof(ReadOnlyBoundToNameValues), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BoundToValues", typeof(ReadOnlyBoundToValues), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReadOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(ValidationFailureResult.Clamp)]
        public ValidationFailureResult OnValidationFailure {
            get {
                return this.onValidationFailureField;
            }
            set {
                this.onValidationFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadOnlyBoundToBoolean {
        
        private string sourceControlField;
        
        private bool inverseField;
        
        private bool inverseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string SourceControl {
            get {
                return this.sourceControlField;
            }
            set {
                this.sourceControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool Inverse {
            get {
                return this.inverseField;
            }
            set {
                this.inverseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InverseSpecified {
            get {
                return this.inverseFieldSpecified;
            }
            set {
                this.inverseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChoiceType {
        
        private string valueField;
        
        private string value1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value1 {
            get {
                return this.value1Field;
            }
            set {
                this.value1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ControlColors {
        
        private string[] colorField;
        
        /// <remarks/>
        // CODEGEN Warning: 'default' attribute on array-like elements is not supported in this version of the .Net Framework.  Ignoring default='#FFFFFF' attribute on element name='Color'.
        [System.Xml.Serialization.XmlElementAttribute("Color", Order=0)]
        public string[] Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadOnlyBoundToNameValues1 {
        
        private string targetControlField;
        
        private string sourceControlField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string TargetControl {
            get {
                return this.targetControlField;
            }
            set {
                this.targetControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string SourceControl {
            get {
                return this.sourceControlField;
            }
            set {
                this.sourceControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadOnlyBoundToNameValues {
        
        private ReadOnlyBoundToNameValues1[] pairField;
        
        private bool inverseField;
        
        private bool inverseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pair", Order=0)]
        public ReadOnlyBoundToNameValues1[] Pair {
            get {
                return this.pairField;
            }
            set {
                this.pairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool Inverse {
            get {
                return this.inverseField;
            }
            set {
                this.inverseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InverseSpecified {
            get {
                return this.inverseFieldSpecified;
            }
            set {
                this.inverseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadOnlyBoundToValues {
        
        private string sourceControlField;
        
        private string commaSeparatedValuesField;
        
        private bool inverseField;
        
        private bool inverseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string SourceControl {
            get {
                return this.sourceControlField;
            }
            set {
                this.sourceControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string CommaSeparatedValues {
            get {
                return this.commaSeparatedValuesField;
            }
            set {
                this.commaSeparatedValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool Inverse {
            get {
                return this.inverseField;
            }
            set {
                this.inverseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InverseSpecified {
            get {
                return this.inverseFieldSpecified;
            }
            set {
                this.inverseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum ValidationFailureResult {
        
        /// <remarks/>
        Ignore,
        
        /// <remarks/>
        Clamp,
        
        /// <remarks/>
        ThrowException,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RadioButton))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DropDown))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class StaticListChoice : BaseControl {
        
        private ChoiceType[] items1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Choice", Order=0)]
        public ChoiceType[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RadioButton : StaticListChoice {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DropDown : StaticListChoice {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkLabel : BaseControl {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FolderChooser : BaseControl {
        
        private string pathField;
        
        public FolderChooser() {
            this.pathField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileChooser : BaseControl {
        
        private string pathField;
        
        private bool allowAllFilesField;
        
        private bool allowAllFilesFieldSpecified;
        
        private string fileTypesField;
        
        public FileChooser() {
            this.pathField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool AllowAllFiles {
            get {
                return this.allowAllFilesField;
            }
            set {
                this.allowAllFilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowAllFilesSpecified {
            get {
                return this.allowAllFilesFieldSpecified;
            }
            set {
                this.allowAllFilesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string FileTypes {
            get {
                return this.fileTypesField;
            }
            set {
                this.fileTypesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TextBox : BaseControl {
        
        private string valueField;
        
        private int maxLengthField;
        
        private bool multilineField;
        
        private bool multilineFieldSpecified;
        
        public TextBox() {
            this.valueField = "";
            this.maxLengthField = 32767;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767)]
        public int MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool Multiline {
            get {
                return this.multilineField;
            }
            set {
                this.multilineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultilineSpecified {
            get {
                return this.multilineFieldSpecified;
            }
            set {
                this.multilineFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVector3RollBallAndSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleVector3Slider))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class DoubleVector3 : BaseControl {
        
        private double xValueField;
        
        private bool xValueFieldSpecified;
        
        private double xMinValueField;
        
        private double xMaxValueField;
        
        private double yValueField;
        
        private bool yValueFieldSpecified;
        
        private double yMinValueField;
        
        private double yMaxValueField;
        
        private bool showResetButtonField;
        
        private double sliderLargeChangeXField;
        
        private bool sliderLargeChangeXFieldSpecified;
        
        private double sliderLargeChangeYField;
        
        private bool sliderLargeChangeYFieldSpecified;
        
        private bool sliderShowTickMarksXField;
        
        private bool sliderShowTickMarksXFieldSpecified;
        
        private bool sliderShowTickMarksYField;
        
        private bool sliderShowTickMarksYFieldSpecified;
        
        private double sliderSmallChangeXField;
        
        private bool sliderSmallChangeXFieldSpecified;
        
        private double sliderSmallChangeYField;
        
        private bool sliderSmallChangeYFieldSpecified;
        
        private double upDownIncrementXField;
        
        private bool upDownIncrementXFieldSpecified;
        
        private double upDownIncrementYField;
        
        private bool upDownIncrementYFieldSpecified;
        
        private double zValueField;
        
        private bool zValueFieldSpecified;
        
        private double zMinValueField;
        
        private double zMaxValueField;
        
        private double sliderLargeChangeZField;
        
        private bool sliderShowTickMarksZField;
        
        private bool sliderShowTickMarksZFieldSpecified;
        
        private double sliderSmallChangeZField;
        
        private double upDownIncrementZField;
        
        public DoubleVector3() {
            this.xMinValueField = -32767D;
            this.xMaxValueField = 32767D;
            this.yMinValueField = -32767D;
            this.yMaxValueField = 32767D;
            this.showResetButtonField = false;
            this.zMinValueField = -32767D;
            this.zMaxValueField = 32767D;
            this.sliderLargeChangeZField = 5D;
            this.sliderSmallChangeZField = 1D;
            this.upDownIncrementZField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double xValue {
            get {
                return this.xValueField;
            }
            set {
                this.xValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xValueSpecified {
            get {
                return this.xValueFieldSpecified;
            }
            set {
                this.xValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double xMinValue {
            get {
                return this.xMinValueField;
            }
            set {
                this.xMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double xMaxValue {
            get {
                return this.xMaxValueField;
            }
            set {
                this.xMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double yValue {
            get {
                return this.yValueField;
            }
            set {
                this.yValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yValueSpecified {
            get {
                return this.yValueFieldSpecified;
            }
            set {
                this.yValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double yMinValue {
            get {
                return this.yMinValueField;
            }
            set {
                this.yMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double yMaxValue {
            get {
                return this.yMaxValueField;
            }
            set {
                this.yMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowResetButton {
            get {
                return this.showResetButtonField;
            }
            set {
                this.showResetButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderLargeChangeX {
            get {
                return this.sliderLargeChangeXField;
            }
            set {
                this.sliderLargeChangeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderLargeChangeXSpecified {
            get {
                return this.sliderLargeChangeXFieldSpecified;
            }
            set {
                this.sliderLargeChangeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderLargeChangeY {
            get {
                return this.sliderLargeChangeYField;
            }
            set {
                this.sliderLargeChangeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderLargeChangeYSpecified {
            get {
                return this.sliderLargeChangeYFieldSpecified;
            }
            set {
                this.sliderLargeChangeYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksX {
            get {
                return this.sliderShowTickMarksXField;
            }
            set {
                this.sliderShowTickMarksXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksXSpecified {
            get {
                return this.sliderShowTickMarksXFieldSpecified;
            }
            set {
                this.sliderShowTickMarksXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksY {
            get {
                return this.sliderShowTickMarksYField;
            }
            set {
                this.sliderShowTickMarksYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksYSpecified {
            get {
                return this.sliderShowTickMarksYFieldSpecified;
            }
            set {
                this.sliderShowTickMarksYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderSmallChangeX {
            get {
                return this.sliderSmallChangeXField;
            }
            set {
                this.sliderSmallChangeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderSmallChangeXSpecified {
            get {
                return this.sliderSmallChangeXFieldSpecified;
            }
            set {
                this.sliderSmallChangeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderSmallChangeY {
            get {
                return this.sliderSmallChangeYField;
            }
            set {
                this.sliderSmallChangeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderSmallChangeYSpecified {
            get {
                return this.sliderSmallChangeYFieldSpecified;
            }
            set {
                this.sliderSmallChangeYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double UpDownIncrementX {
            get {
                return this.upDownIncrementXField;
            }
            set {
                this.upDownIncrementXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpDownIncrementXSpecified {
            get {
                return this.upDownIncrementXFieldSpecified;
            }
            set {
                this.upDownIncrementXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double UpDownIncrementY {
            get {
                return this.upDownIncrementYField;
            }
            set {
                this.upDownIncrementYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpDownIncrementYSpecified {
            get {
                return this.upDownIncrementYFieldSpecified;
            }
            set {
                this.upDownIncrementYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double zValue {
            get {
                return this.zValueField;
            }
            set {
                this.zValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zValueSpecified {
            get {
                return this.zValueFieldSpecified;
            }
            set {
                this.zValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double zMinValue {
            get {
                return this.zMinValueField;
            }
            set {
                this.zMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double zMaxValue {
            get {
                return this.zMaxValueField;
            }
            set {
                this.zMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(5D)]
        public double SliderLargeChangeZ {
            get {
                return this.sliderLargeChangeZField;
            }
            set {
                this.sliderLargeChangeZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksZ {
            get {
                return this.sliderShowTickMarksZField;
            }
            set {
                this.sliderShowTickMarksZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksZSpecified {
            get {
                return this.sliderShowTickMarksZFieldSpecified;
            }
            set {
                this.sliderShowTickMarksZFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double SliderSmallChangeZ {
            get {
                return this.sliderSmallChangeZField;
            }
            set {
                this.sliderSmallChangeZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double UpDownIncrementZ {
            get {
                return this.upDownIncrementZField;
            }
            set {
                this.upDownIncrementZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoubleVector3RollBallAndSlider : DoubleVector3 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoubleVector3Slider : DoubleVector3 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoubleVectorPanAndSlider : BaseControl {
        
        private double xValueField;
        
        private bool xValueFieldSpecified;
        
        private double xMinValueField;
        
        private double xMaxValueField;
        
        private double yValueField;
        
        private bool yValueFieldSpecified;
        
        private double yMinValueField;
        
        private double yMaxValueField;
        
        private bool showResetButtonField;
        
        private double sliderLargeChangeXField;
        
        private bool sliderLargeChangeXFieldSpecified;
        
        private double sliderLargeChangeYField;
        
        private bool sliderLargeChangeYFieldSpecified;
        
        private bool sliderShowTickMarksXField;
        
        private bool sliderShowTickMarksXFieldSpecified;
        
        private bool sliderShowTickMarksYField;
        
        private bool sliderShowTickMarksYFieldSpecified;
        
        private double sliderSmallChangeXField;
        
        private bool sliderSmallChangeXFieldSpecified;
        
        private double sliderSmallChangeYField;
        
        private bool sliderSmallChangeYFieldSpecified;
        
        private double upDownIncrementXField;
        
        private bool upDownIncrementXFieldSpecified;
        
        private double upDownIncrementYField;
        
        private bool upDownIncrementYFieldSpecified;
        
        private byte[] staticImageUnderlayField;
        
        public DoubleVectorPanAndSlider() {
            this.xMinValueField = -32767D;
            this.xMaxValueField = 32767D;
            this.yMinValueField = -32767D;
            this.yMaxValueField = 32767D;
            this.showResetButtonField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double xValue {
            get {
                return this.xValueField;
            }
            set {
                this.xValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xValueSpecified {
            get {
                return this.xValueFieldSpecified;
            }
            set {
                this.xValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double xMinValue {
            get {
                return this.xMinValueField;
            }
            set {
                this.xMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double xMaxValue {
            get {
                return this.xMaxValueField;
            }
            set {
                this.xMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double yValue {
            get {
                return this.yValueField;
            }
            set {
                this.yValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yValueSpecified {
            get {
                return this.yValueFieldSpecified;
            }
            set {
                this.yValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double yMinValue {
            get {
                return this.yMinValueField;
            }
            set {
                this.yMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double yMaxValue {
            get {
                return this.yMaxValueField;
            }
            set {
                this.yMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowResetButton {
            get {
                return this.showResetButtonField;
            }
            set {
                this.showResetButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderLargeChangeX {
            get {
                return this.sliderLargeChangeXField;
            }
            set {
                this.sliderLargeChangeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderLargeChangeXSpecified {
            get {
                return this.sliderLargeChangeXFieldSpecified;
            }
            set {
                this.sliderLargeChangeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderLargeChangeY {
            get {
                return this.sliderLargeChangeYField;
            }
            set {
                this.sliderLargeChangeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderLargeChangeYSpecified {
            get {
                return this.sliderLargeChangeYFieldSpecified;
            }
            set {
                this.sliderLargeChangeYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksX {
            get {
                return this.sliderShowTickMarksXField;
            }
            set {
                this.sliderShowTickMarksXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksXSpecified {
            get {
                return this.sliderShowTickMarksXFieldSpecified;
            }
            set {
                this.sliderShowTickMarksXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksY {
            get {
                return this.sliderShowTickMarksYField;
            }
            set {
                this.sliderShowTickMarksYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksYSpecified {
            get {
                return this.sliderShowTickMarksYFieldSpecified;
            }
            set {
                this.sliderShowTickMarksYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderSmallChangeX {
            get {
                return this.sliderSmallChangeXField;
            }
            set {
                this.sliderSmallChangeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderSmallChangeXSpecified {
            get {
                return this.sliderSmallChangeXFieldSpecified;
            }
            set {
                this.sliderSmallChangeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderSmallChangeY {
            get {
                return this.sliderSmallChangeYField;
            }
            set {
                this.sliderSmallChangeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderSmallChangeYSpecified {
            get {
                return this.sliderSmallChangeYFieldSpecified;
            }
            set {
                this.sliderSmallChangeYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double UpDownIncrementX {
            get {
                return this.upDownIncrementXField;
            }
            set {
                this.upDownIncrementXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpDownIncrementXSpecified {
            get {
                return this.upDownIncrementXFieldSpecified;
            }
            set {
                this.upDownIncrementXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double UpDownIncrementY {
            get {
                return this.upDownIncrementYField;
            }
            set {
                this.upDownIncrementYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpDownIncrementYSpecified {
            get {
                return this.upDownIncrementYFieldSpecified;
            }
            set {
                this.upDownIncrementYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="base64Binary")]
        public byte[] StaticImageUnderlay {
            get {
                return this.staticImageUnderlayField;
            }
            set {
                this.staticImageUnderlayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoubleVectorSlider : BaseControl {
        
        private double xValueField;
        
        private bool xValueFieldSpecified;
        
        private double xMinValueField;
        
        private double xMaxValueField;
        
        private double yValueField;
        
        private bool yValueFieldSpecified;
        
        private double yMinValueField;
        
        private double yMaxValueField;
        
        private bool showResetButtonField;
        
        private double sliderLargeChangeXField;
        
        private bool sliderLargeChangeXFieldSpecified;
        
        private double sliderLargeChangeYField;
        
        private bool sliderLargeChangeYFieldSpecified;
        
        private bool sliderShowTickMarksXField;
        
        private bool sliderShowTickMarksXFieldSpecified;
        
        private bool sliderShowTickMarksYField;
        
        private bool sliderShowTickMarksYFieldSpecified;
        
        private double sliderSmallChangeXField;
        
        private bool sliderSmallChangeXFieldSpecified;
        
        private double sliderSmallChangeYField;
        
        private bool sliderSmallChangeYFieldSpecified;
        
        private double upDownIncrementXField;
        
        private bool upDownIncrementXFieldSpecified;
        
        private double upDownIncrementYField;
        
        private bool upDownIncrementYFieldSpecified;
        
        private int decimalPlacesField;
        
        private bool useExponentialScaleField;
        
        private bool useExponentialScaleFieldSpecified;
        
        public DoubleVectorSlider() {
            this.xMinValueField = -32767D;
            this.xMaxValueField = 32767D;
            this.yMinValueField = -32767D;
            this.yMaxValueField = 32767D;
            this.showResetButtonField = false;
            this.decimalPlacesField = 2;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double xValue {
            get {
                return this.xValueField;
            }
            set {
                this.xValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xValueSpecified {
            get {
                return this.xValueFieldSpecified;
            }
            set {
                this.xValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double xMinValue {
            get {
                return this.xMinValueField;
            }
            set {
                this.xMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double xMaxValue {
            get {
                return this.xMaxValueField;
            }
            set {
                this.xMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double yValue {
            get {
                return this.yValueField;
            }
            set {
                this.yValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yValueSpecified {
            get {
                return this.yValueFieldSpecified;
            }
            set {
                this.yValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32767D)]
        public double yMinValue {
            get {
                return this.yMinValueField;
            }
            set {
                this.yMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double yMaxValue {
            get {
                return this.yMaxValueField;
            }
            set {
                this.yMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowResetButton {
            get {
                return this.showResetButtonField;
            }
            set {
                this.showResetButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderLargeChangeX {
            get {
                return this.sliderLargeChangeXField;
            }
            set {
                this.sliderLargeChangeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderLargeChangeXSpecified {
            get {
                return this.sliderLargeChangeXFieldSpecified;
            }
            set {
                this.sliderLargeChangeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderLargeChangeY {
            get {
                return this.sliderLargeChangeYField;
            }
            set {
                this.sliderLargeChangeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderLargeChangeYSpecified {
            get {
                return this.sliderLargeChangeYFieldSpecified;
            }
            set {
                this.sliderLargeChangeYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksX {
            get {
                return this.sliderShowTickMarksXField;
            }
            set {
                this.sliderShowTickMarksXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksXSpecified {
            get {
                return this.sliderShowTickMarksXFieldSpecified;
            }
            set {
                this.sliderShowTickMarksXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarksY {
            get {
                return this.sliderShowTickMarksYField;
            }
            set {
                this.sliderShowTickMarksYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksYSpecified {
            get {
                return this.sliderShowTickMarksYFieldSpecified;
            }
            set {
                this.sliderShowTickMarksYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderSmallChangeX {
            get {
                return this.sliderSmallChangeXField;
            }
            set {
                this.sliderSmallChangeXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderSmallChangeXSpecified {
            get {
                return this.sliderSmallChangeXFieldSpecified;
            }
            set {
                this.sliderSmallChangeXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double SliderSmallChangeY {
            get {
                return this.sliderSmallChangeYField;
            }
            set {
                this.sliderSmallChangeYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderSmallChangeYSpecified {
            get {
                return this.sliderSmallChangeYFieldSpecified;
            }
            set {
                this.sliderSmallChangeYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double UpDownIncrementX {
            get {
                return this.upDownIncrementXField;
            }
            set {
                this.upDownIncrementXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpDownIncrementXSpecified {
            get {
                return this.upDownIncrementXFieldSpecified;
            }
            set {
                this.upDownIncrementXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double UpDownIncrementY {
            get {
                return this.upDownIncrementYField;
            }
            set {
                this.upDownIncrementYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpDownIncrementYSpecified {
            get {
                return this.upDownIncrementYFieldSpecified;
            }
            set {
                this.upDownIncrementYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(2)]
        public int DecimalPlaces {
            get {
                return this.decimalPlacesField;
            }
            set {
                this.decimalPlacesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool UseExponentialScale {
            get {
                return this.useExponentialScaleField;
            }
            set {
                this.useExponentialScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseExponentialScaleSpecified {
            get {
                return this.useExponentialScaleFieldSpecified;
            }
            set {
                this.useExponentialScaleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBox : BaseControl {
        
        private bool valueField;
        
        private bool valueFieldSpecified;
        
        private string footnoteField;
        
        public CheckBox() {
            this.footnoteField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Footnote {
            get {
                return this.footnoteField;
            }
            set {
                this.footnoteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncrementButton : BaseControl {
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        private int minValueField;
        
        private int maxValueField;
        
        private string buttonTextField;
        
        public IncrementButton() {
            this.minValueField = -2147483648;
            this.maxValueField = 2147483647;
            this.buttonTextField = "+";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(2147483647)]
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("+")]
        public string ButtonText {
            get {
                return this.buttonTextField;
            }
            set {
                this.buttonTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ColorWheel : BaseControl {
        
        private string valueField;
        
        private int minValueField;
        
        private int maxValueField;
        
        private bool alphaField;
        
        private bool showResetButtonField;
        
        public ColorWheel() {
            this.valueField = "#00000000";
            this.minValueField = -2147483648;
            this.maxValueField = 2147483647;
            this.alphaField = true;
            this.showResetButtonField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute("#00000000")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(2147483647)]
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Alpha {
            get {
                return this.alphaField;
            }
            set {
                this.alphaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ShowResetButton {
            get {
                return this.showResetButtonField;
            }
            set {
                this.showResetButtonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleSlider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntSlider))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseSlider : BaseControl {
        
        private ControlColors controlColorsField;
        
        private SliderControlStyle controlStyleField;
        
        private bool rangeWrapsField;
        
        private bool rangeWrapsFieldSpecified;
        
        private bool showResetButtonField;
        
        private double sliderLargeChangeField;
        
        private double sliderSmallChangeField;
        
        private double upDownIncrementField;
        
        public BaseSlider() {
            this.controlStyleField = SliderControlStyle.Default;
            this.showResetButtonField = true;
            this.sliderLargeChangeField = 5D;
            this.sliderSmallChangeField = 1D;
            this.upDownIncrementField = 1D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ControlColors ControlColors {
            get {
                return this.controlColorsField;
            }
            set {
                this.controlColorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(SliderControlStyle.Default)]
        public SliderControlStyle ControlStyle {
            get {
                return this.controlStyleField;
            }
            set {
                this.controlStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool RangeWraps {
            get {
                return this.rangeWrapsField;
            }
            set {
                this.rangeWrapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RangeWrapsSpecified {
            get {
                return this.rangeWrapsFieldSpecified;
            }
            set {
                this.rangeWrapsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ShowResetButton {
            get {
                return this.showResetButtonField;
            }
            set {
                this.showResetButtonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(5D)]
        public double SliderLargeChange {
            get {
                return this.sliderLargeChangeField;
            }
            set {
                this.sliderLargeChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double SliderSmallChange {
            get {
                return this.sliderSmallChangeField;
            }
            set {
                this.sliderSmallChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double UpDownIncrement {
            get {
                return this.upDownIncrementField;
            }
            set {
                this.upDownIncrementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum SliderControlStyle {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Hue,
        
        /// <remarks/>
        HueCentered,
        
        /// <remarks/>
        SaturationHue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoubleSlider : BaseSlider {
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        private double minValueField;
        
        private double maxValueField;
        
        private int decimalPlacesField;
        
        private bool useExponentialScaleField;
        
        private bool useExponentialScaleFieldSpecified;
        
        public DoubleSlider() {
            this.minValueField = -32768D;
            this.maxValueField = 32767D;
            this.decimalPlacesField = 2;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-32768D)]
        public double MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(32767D)]
        public double MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(2)]
        public int DecimalPlaces {
            get {
                return this.decimalPlacesField;
            }
            set {
                this.decimalPlacesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool UseExponentialScale {
            get {
                return this.useExponentialScaleField;
            }
            set {
                this.useExponentialScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseExponentialScaleSpecified {
            get {
                return this.useExponentialScaleFieldSpecified;
            }
            set {
                this.useExponentialScaleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntSlider : BaseSlider {
        
        private int valueField;
        
        private bool valueFieldSpecified;
        
        private int minValueField;
        
        private int maxValueField;
        
        private bool sliderShowTickMarksField;
        
        private bool sliderShowTickMarksFieldSpecified;
        
        public IntSlider() {
            this.minValueField = -2147483648;
            this.maxValueField = 2147483647;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(2147483647)]
        public int MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool SliderShowTickMarks {
            get {
                return this.sliderShowTickMarksField;
            }
            set {
                this.sliderShowTickMarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SliderShowTickMarksSpecified {
            get {
                return this.sliderShowTickMarksFieldSpecified;
            }
            set {
                this.sliderShowTickMarksFieldSpecified = value;
            }
        }
    }
}
